<!DOCTYPE html>
<html>

  <head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title>Add Twisted Cube with C#</title>
  <meta name="description" content="Demonstrates how to construct a twisted cube object from an array of points and a list of curves.  Using C#">

  <!-- OpenGraph for Facebook, Twitter, Slack unfurling -->
  <meta property="og:type" content="website" />
  <meta property="og:url" content="/samples/rhinocommon/add-twisted-cube/" />
  <meta property="og:title" content="Add Twisted Cube" />
  <meta property="og:description" content="Demonstrates how to construct a twisted cube object from an array of points and a list of curves." />
  <meta property=”og:site_name” content="developer.rhino3d.com"/>
  <meta property=”og:image” content="/images/rhinodev-logo-unfurl.png"/>

  <!-- twitter card tags additive with the og: tags -->
  <meta name="twitter:domain" value="developer.rhino3d.com" />
  <meta name="twitter:title" value="Add Twisted Cube" />
  <meta name="twitter:description" value="Demonstrates how to construct a twisted cube object from an array of points and a list of curves." />
  
    <meta name="twitter:image" content="/images/rhinodev-logo-unfurl.png" />
  
  <meta name="twitter:url" value="http://developer.rhino3d.com" />
  
  <meta name="twitter:label1" value="Platform(s)" />
  <meta name="twitter:data1" value="Windows, Mac" />
  
  
  <meta name="twitter:label2" value="Language(s)" />
  <meta name="twitter:data2" value="C#" />
  

  <link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/highlight.js/8.6/styles/github.min.css">
  <script type="text/javascript" src="http://cdnjs.cloudflare.com/ajax/libs/highlight.js/8.6/highlight.min.js"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/8.5/languages/vbnet.min.js"></script>
  <script src="/node_modules/highlightjs-line-numbers.js/dist/highlightjs-line-numbers.min.js"></script>
  <script>hljs.initHighlightingOnLoad();</script>
  <script>hljs.initLineNumbersOnLoad();</script>

  <!-- Overridden theme -->
  <link rel="stylesheet" href="/css/main.css">

  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap-theme.min.css">
  <!-- Bootstrap override -->
  <link rel="stylesheet" href="/css/bootstrap-override.css">

  <link rel="canonical" href="http://developer.rhino3d.com/samples/rhinocommon/add-twisted-cube/">
  <link rel="alternate" type="application/rss+xml" title="Rhino Developer Docs" href="http://developer.rhino3d.com/feed.xml" />

  <link rel="shortcut icon" href="http://developer.rhino3d.com/favicon.ico?v=2" />
  <!-- Saving bookmarks to mobile devices -->
  <!-- For non-Retina (@1× display) iPhone, iPod Touch, and Android 2.1+ devices: -->
  <link rel="apple-touch-icon-precomposed" href="/images/apple-touch-icon-precomposed.png"><!-- 57×57px -->
  <!-- For the iPad mini and the first- and second-generation iPad (@1× display) on iOS ≤ 6: -->
  <link rel="apple-touch-icon-precomposed" sizes="72x72" href="/images/apple-touch-icon-72x72-precomposed.png">
  <!-- For the iPad mini and the first- and second-generation iPad (@1× display) on iOS ≥ 7: -->
  <link rel="apple-touch-icon-precomposed" sizes="76x76" href="/images/apple-touch-icon-76x76-precomposed.png">
  <!-- For iPhone with @2× display running iOS ≤ 6: -->
  <link rel="apple-touch-icon-precomposed" sizes="114x114" href="/images/apple-touch-icon-114x114-precomposed.png">
  <!-- For iPhone with @2× display running iOS ≥ 7: -->
  <link rel="apple-touch-icon-precomposed" sizes="120x120" href="/images/apple-touch-icon-120x120-precomposed.png">
  <!-- For iPad with @2× display running iOS ≤ 6: -->
  <link rel="apple-touch-icon-precomposed" sizes="144x144" href="/images/apple-touch-icon-144x144-precomposed.png">
  <!-- For iPad with @2× display running iOS ≥ 7: -->
  <link rel="apple-touch-icon-precomposed" sizes="152x152" href="/images/apple-touch-icon-152x152-precomposed.png">
  <!-- For iPhone 6 Plus with @3× display: -->
  <link rel="apple-touch-icon-precomposed" sizes="180x180" href="/images/apple-touch-icon-180x180-precomposed.png">
  <!-- For Chrome for Android: -->
  <link rel="icon" sizes="192x192" href="images/touch-icon-192x192.png">

</head>


  <body>

    <!-- Google Tag Manager **This belongs right after the <body> tag**-->
    <noscript>
        <iframe src="//www.googletagmanager.com/ns.html?id=GTM-MWMDKN"
        height="0" width="0" style="display:none;visibility:hidden"></iframe>
    </noscript>
    <script>
        (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
        new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
        j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
        '//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
        })(window,document,'script','dataLayer','GTM-MWMDKN');
    </script>
    <!-- End Google Tag Manager -->


    


    <div class="container">

      <header class="site-header">


    <a class="site-title" href="/"><img src="/images/rhinodevlogo148x128.png" alt="Rhino Developer Docs" height="48" width="56"></a><a class="site-title" href="/">Rhino Developer Docs</a>

    <nav class="site-nav">
      <img class="menu-icon" src="/images/gi.svg">
      
      <div class="trigger">
      	<!--<a class="page-link" href="/">Welcome</a>-->
        <!-- get current page title and "collection" to figure out which nav
             link should be "active" -->
        
        
        
        
          
            
              
            
          
        
          
            
              
            
          
        
          
            
              
            
          
        
          
            
              
            
          
        
          
            
              
            
          
        
          
            
              
            
          
        
          
            
              
            
          
        
          
            
              
            
          
        
          
            
              
            
          
        
          
        
          
            
              
                
                  <a class="page-link" href="/guides/">Guides</a>
                
              
            
          
        
          
            
              
                
                  <a class="page-link" href="/api/">API</a>
                
              
            
          
        
          
            
              
                
                  <a class="page-link active" href="/samples/">Samples</a>
                
              
            
          
        
          
            
          
        
          
            
              
                
                  <a class="page-link" href="/videos/">Videos</a>
                
              
            
          
        
        <a class="page-link" href="http://discourse.mcneel.com/c/rhino-developer">Forums</a>
        <!-- Google Search Engine -->
        <!-- TODO Move to this site back into the Mcneel search, or use a simple site only search for results -->
        <div id="sitesearch">
            <!-- Google CSE Search Box Begins  -->
            <!-- Use of this code assumes agreement with the Google Custom Search Terms of Service. -->
            <!-- The terms of service are available at https://www.google.com/cse/docs/tos.html -->
            <form id="cref" action="/search-results.html">
                <input type="hidden" name="cref" value="007988927381198593803:mcq6pshqsn8" />
                <input id="searchtext" type="text" name="q" size="24" value="" placeholder="search" />
                <input class="searchBox" type="submit" name="sa" size="2" value=" " />
            </form>
        <!-- Google CSE Search Box Ends -->
        </div>
        <!--End of Google Search Engine -->
      </div>
    </nav>

</header>


      <div class="page-content">
        <!--div class="wrapper"-->
          <h3>Add Twisted Cube</h3>

<p>Demonstrates how to construct a twisted cube object from an array of points and a list of curves.</p>

<ul class="nav nav-pills">
  <li class="active"><a href="#cs" data-toggle="pill">C#</a></li>
  <li><a href="#vb" data-toggle="pill">VB.NET</a></li>
  <li><a href="#py" data-toggle="pill">Python</a></li>
</ul>

<div class="tab-content">
  <pre class="tab-pane fade in active" id="cs"><code class="language-cs">partial class Examples
{
  // Symbolic vertex index constants to make code more readable
  const int A = 0, B = 1, C = 2, D = 3, E = 4, F = 5, G = 6, H = 7;

  // Symbolic edge index constants to make code more readable
  const int AB = 0, BC = 1, CD = 2, AD = 3, EF = 4, FG = 5, GH = 6,
    EH = 7, AE = 8, BF = 9, CG = 10, DH = 11;

  // Symbolic face index constants to make code more readable
  const int ABCD = 0, BCGF = 1, CDHG = 2, ADHE = 3, ABFE = 4, EFGH = 5;


  public static Rhino.Commands.Result AddTwistedCube(Rhino.RhinoDoc doc)
  {
    Point3d[] points = new Point3d[8];
    points[0] = new Point3d(0.0, 0.0, 0.0);   // point A = geometry for vertex 0
    points[1] = new Point3d(10.0, 0.0, 0.0);  // point B = geometry for vertex 1
    points[2] = new Point3d(10.0, 8.0, -1.0); // point C = geometry for vertex 2
    points[3] = new Point3d(0.0, 6.0, 0.0);   // point D = geometry for vertex 3
    points[4] = new Point3d(1.0, 2.0, 11.0);  // point E = geometry for vertex 4
    points[5] = new Point3d(10.0, 0.0, 12.0); // point F = geometry for vertex 5
    points[6] = new Point3d(10.0, 7.0, 13.0); // point G = geometry for vertex 6
    points[7] = new Point3d(0.0, 6.0, 12.0);  // point H = geometry for vertex 7

    Brep brep = new Brep();

    // Create eight vertices located at the eight points
    for (int vi = 0; vi &lt; 8; vi++)
      brep.Vertices.Add(points[vi], 0.0);

    // Create 3d curve geometry - the orientations are arbitrarily chosen
    // so that the end vertices are in alphabetical order.
    brep.Curves3D.Add(TwistedCubeEdgeCurve(points[A], points[B])); // line AB
    brep.Curves3D.Add(TwistedCubeEdgeCurve(points[B], points[C])); // line BC
    brep.Curves3D.Add(TwistedCubeEdgeCurve(points[C], points[D])); // line CD
    brep.Curves3D.Add(TwistedCubeEdgeCurve(points[A], points[D])); // line AD
    brep.Curves3D.Add(TwistedCubeEdgeCurve(points[E], points[F])); // line EF
    brep.Curves3D.Add(TwistedCubeEdgeCurve(points[F], points[G])); // line FG
    brep.Curves3D.Add(TwistedCubeEdgeCurve(points[G], points[H])); // line GH
    brep.Curves3D.Add(TwistedCubeEdgeCurve(points[E], points[H])); // line EH
    brep.Curves3D.Add(TwistedCubeEdgeCurve(points[A], points[E])); // line AE
    brep.Curves3D.Add(TwistedCubeEdgeCurve(points[B], points[F])); // line BF
    brep.Curves3D.Add(TwistedCubeEdgeCurve(points[C], points[G])); // line CG
    brep.Curves3D.Add(TwistedCubeEdgeCurve(points[D], points[H])); // line DH

    // Create the 12 edges that connect the corners of the cube.
    MakeTwistedCubeEdges(ref brep);

    // Create 3d surface geometry - the orientations are arbitrarily chosen so
    // that some normals point into the cube and others point out of the cube.
    brep.AddSurface(TwistedCubeSideSurface(points[A], points[B], points[C], points[D])); // ABCD
    brep.AddSurface(TwistedCubeSideSurface(points[B], points[C], points[G], points[F])); // BCGF
    brep.AddSurface(TwistedCubeSideSurface(points[C], points[D], points[H], points[G])); // CDHG
    brep.AddSurface(TwistedCubeSideSurface(points[A], points[D], points[H], points[E])); // ADHE
    brep.AddSurface(TwistedCubeSideSurface(points[A], points[B], points[F], points[E])); // ABFE
    brep.AddSurface(TwistedCubeSideSurface(points[E], points[F], points[G], points[H])); // EFGH

    // Create the CRhinoBrepFaces
    MakeTwistedCubeFaces(ref brep);

    if (brep.IsValid)
    {
      doc.Objects.AddBrep(brep);
      doc.Views.Redraw();
      return Rhino.Commands.Result.Success;
    }
    return Rhino.Commands.Result.Failure;
  }

  static Curve TwistedCubeEdgeCurve(Point3d from, Point3d to)
  {
    // Create a 3d line segment to be used as a 3d curve in a Brep
    return new LineCurve(from, to) { Domain = new Interval(0, 1) };
  }

  static void MakeTwistedCubeEdges(ref Brep brep)
  {
    // In this simple example, the edge indices exactly match the 3d curve
    // indices.  In general,the correspondence between edge and curve indices
    // can be arbitrary.  It is permitted for multiple edges to use different
    // portions of the same 3d curve.  The orientation of the edge always
    // agrees with the natural parametric orientation of the curve.
    brep.Edges.Add(A, B, AB, 0); // Edge that runs from A to B
    brep.Edges.Add(B, C, BC, 0); // Edge that runs from B to C
    brep.Edges.Add(C, D, CD, 0); // Edge that runs from C to D
    brep.Edges.Add(A, D, AD, 0); // Edge that runs from A to D
    brep.Edges.Add(E, F, EF, 0); // Edge that runs from E to F
    brep.Edges.Add(F, G, FG, 0); // Edge that runs from F to G
    brep.Edges.Add(G, H, GH, 0); // Edge that runs from G to H
    brep.Edges.Add(E, H, EH, 0); // Edge that runs from E to H
    brep.Edges.Add(A, E, AE, 0); // Edge that runs from A to E
    brep.Edges.Add(B, F, BF, 0); // Edge that runs from B to F
    brep.Edges.Add(C, G, CG, 0); // Edge that runs from C to G
    brep.Edges.Add(D, H, DH, 0); // Edge that runs from D to H
  }

  static Surface TwistedCubeSideSurface(Point3d southwest, Point3d southeast, Point3d northeast, Point3d northwest)
  {
    var ns = NurbsSurface.Create(3, false, 2, 2, 2, 2);

    // Corner CVs in counter clockwise order starting in the south west
    ns.Points.SetControlPoint(0, 0, southwest);
    ns.Points.SetControlPoint(1, 0, southeast);
    ns.Points.SetControlPoint(1, 1, northeast);
    ns.Points.SetControlPoint(0, 1, northwest);

    // "u" knots
    ns.KnotsU[0] = 0.0;
    ns.KnotsU[1] = 1.0;

    // "v" knots
    ns.KnotsV[0] = 0;
    ns.KnotsV[1] = 1;
    return ns;
  }

  static void MakeTwistedCubeFaces(ref Brep brep)
  {
    MakeTwistedCubeFace(ref brep,
      ABCD,       // Index of surface ABCD
      +1, // Indices of vertices listed in SW,SE,NW,NE order
      AB, +1,     // South side edge and its orientation with respect to
      // to the trimming curve.  (AB)
      BC, +1,     // South side edge and its orientation with respect to
      // to the trimming curve.  (BC)
      CD, +1,     // South side edge and its orientation with respect to
      // to the trimming curve   (CD)
      AD, -1      // South side edge and its orientation with respect to
      // to the trimming curve   (AD)
      );

    MakeTwistedCubeFace(ref brep,
      BCGF,       // Index of surface BCGF
      -1, // Indices of vertices listed in SW,SE,NW,NE order
      BC, +1,     // South side edge and its orientation with respect to
      // to the trimming curve.  (BC)
      CG, +1,     // South side edge and its orientation with respect to
      // to the trimming curve.  (CG)
      FG, -1,     // South side edge and its orientation with respect to
      // to the trimming curve   (FG)
      BF, -1      // South side edge and its orientation with respect to
      // to the trimming curve   (BF)
      );

    MakeTwistedCubeFace(ref brep,
      CDHG,       // Index of surface CDHG
      -1, // Indices of vertices listed in SW,SE,NW,NE order
      CD, +1,     // South side edge and its orientation with respect to
      // to the trimming curve.  (CD)
      DH, +1,     // South side edge and its orientation with respect to
      // to the trimming curve.  (DH)
      GH, -1,     // South side edge and its orientation with respect to
      // to the trimming curve   (GH)
      CG, -1      // South side edge and its orientation with respect to
      // to the trimming curve   (CG)
      );

    MakeTwistedCubeFace(ref brep,
      ADHE,       // Index of surface ADHE
      +1, // Indices of vertices listed in SW,SE,NW,NE order
      AD, +1,     // South side edge and its orientation with respect to
      // to the trimming curve.  (AD)
      DH, +1,     // South side edge and its orientation with respect to
      // to the trimming curve.  (DH)
      EH, -1,     // South side edge and its orientation with respect to
      // to the trimming curve   (EH)
      AE, -1      // South side edge and its orientation with respect to
      // to the trimming curve   (AE)
      );

    MakeTwistedCubeFace(ref brep,
      ABFE,       // Index of surface ABFE
      -1, // Indices of vertices listed in SW,SE,NW,NE order
      AB, +1,     // South side edge and its orientation with respect to
      // to the trimming curve.  (AB)
      BF, +1,     // South side edge and its orientation with respect to
      // to the trimming curve.  (BF)
      EF, -1,     // South side edge and its orientation with respect to
      // to the trimming curve   (EF)
      AE, -1      // South side edge and its orientation with respect to
      // to the trimming curve   (AE)
      );

    MakeTwistedCubeFace(ref brep,
      EFGH,       // Index of surface EFGH
      -1, // Indices of vertices listed in SW,SE,NW,NE order
      EF, +1,     // South side edge and its orientation with respect to
      // to the trimming curve.  (EF)
      FG, +1,     // South side edge and its orientation with respect to
      // to the trimming curve.  (FG)
      GH, +1,     // South side edge and its orientation with respect to
      // to the trimming curve   (GH)
      EH, -1      // South side edge and its orientation with respect to
      // to the trimming curve   (EH)
      );
  }

  static void MakeTwistedCubeFace( ref Brep brep, int surfaceIndex,
    int s_dir,   // Indices of corner vertices listed in SW, SE, NW, NE order
    int southEdgeIndex,
    int eS_dir,  // orientation of edge with respect to surface trim
    int eastEdgeIndex,
    int eE_dir,  // orientation of edge with respect to surface trim
    int northEdgeIndex,
    int eN_dir,  // orientation of edge with respect to surface trim
    int westEdgeIndex,
    int eW_dir   // orientation of edge with respect to surface trim
    )
  {
    var face = brep.Faces.Add(surfaceIndex);

    MakeTwistedCubeTrimmingLoop(
      ref brep,
      ref face,
      southEdgeIndex, eS_dir,
      eastEdgeIndex, eE_dir,
      northEdgeIndex, eN_dir,
      westEdgeIndex, eW_dir
      );

    face.OrientationIsReversed = (s_dir == -1);
  }

  static void MakeTwistedCubeTrimmingLoop( ref Brep brep, ref BrepFace face, // Indices of corner vertices listed in SW, SE, NW, NE order
  int eSi,     // index of edge on south side of surface
  int eS_dir,  // orientation of edge with respect to surface trim
  int eEi,     // index of edge on south side of surface
  int eE_dir,  // orientation of edge with respect to surface trim
  int eNi,     // index of edge on south side of surface
  int eN_dir,  // orientation of edge with respect to surface trim
  int eWi,     // index of edge on south side of surface
  int eW_dir   // orientation of edge with respect to surface trim
                               )
  {
    Surface srf = brep.Surfaces[face.SurfaceIndex];
    var loop = brep.Loops.Add(BrepLoopType.Outer, face);

    // Create trimming curves running counter clockwise around the surface's domain.
    // Start at the south side
    // side: 0=south, 1=east, 2=north, 3=west
    for (int side = 0; side &lt; 4; side++)
    {
      Curve trimming_curve = TwistedCubeTrimmingCurve(srf, side);
      int curve_index = brep.Curves2D.Add(trimming_curve);

      int ei = 0;
      bool reverse = false;
      IsoStatus iso = IsoStatus.None;
      switch (side)
      {
        case 0: // south
          ei = eSi;
          reverse = (eS_dir == -1);
          iso = IsoStatus.South;
          break;
        case 1: // east
          ei = eEi;
          reverse = (eE_dir == -1);
          iso = IsoStatus.East;
          break;
        case 2: // north
          ei = eNi;
          reverse = (eN_dir == -1);
          iso = IsoStatus.North;
          break;
        case 3: // west
          ei = eWi;
          reverse = (eW_dir == -1);
          iso = IsoStatus.West;
          break;
      }

      BrepEdge edge = brep.Edges[ei];
      BrepTrim trim = brep.Trims.Add(edge, reverse, loop, curve_index);
      trim.IsoStatus = iso;
      trim.TrimType = BrepTrimType.Mated; // This b-rep is closed, so all trims have mates.
      trim.SetTolerances(0, 0); // This simple example is exact - for models with
      // non-exact data, set tolerance as explained in
      // definition of BrepTrim.
    }
  }

  static Curve TwistedCubeTrimmingCurve(Surface s, int side // 0 = SW to SE
    // 1 = SE to NE
    // 2 = NE to NW
    // 3 = NW to SW
    )
  {
    // A trimming curve is a 2d curve whose image lies in the surface's domain.
    // The "active" portion of the surface is to the left of the trimming curve.
    // An outer trimming loop consists of a simple closed curve running
    // counter-clockwise around the region it trims.
    var u_domain = s.Domain(0);
    var v_domain = s.Domain(1);
    double u0 = u_domain[0];
    double u1 = u_domain[1];
    double v0 = v_domain[0];
    double v1 = v_domain[1];

    Point2d from;
    Point2d to;

    switch (side)
    {
      case 0:  // SW to SE
        from = new Point2d(u0, v0);
        to = new Point2d(u1, v0);
        break;
      case 1: // SE to NE
        from = new Point2d(u1, v0);
        to = new Point2d(u1, v1);
        break;
      case 2: // NE to NW
        from = new Point2d(u1, v1);
        to = new Point2d(u0, v1);
        break;
      case 3: // NW to SW
        from = new Point2d(u0, v1);
        to = new Point2d(u0, v0);
        break;
      default:
        return null;
    }

    return new LineCurve(from, to) { Domain = new Interval(0, 1) };
  }

}
</code></pre>

<pre class="tab-pane fade in" id="vb"><code class="language-vbnet">' No VB.NET sample available
</code></pre>

<pre class="tab-pane fade in" id="py"><code class="language-python"># No Python sample available
</code></pre>

</div>

        <!--/div-->
      </div>

      <footer class="site-footer">

  <div class="wrapper">

    <div class="footer-col-wrapper">

      
        <div class="row">
          <div class="col-md-4">

            <p class="text">
              
                Author: <a href="https://discourse.mcneel.com/users/stevebaer/activity">Steve Baer</a>
              
            </p>
          </div>
          <div class="col-md-4 text-center">
            <span class="icon  icon--github">
              <svg viewBox="0 0 16 16">
                <path fill="#828282" d="M7.999,0.431c-4.285,0-7.76,3.474-7.76,7.761 c0,3.428,2.223,6.337,5.307,7.363c0.388,0.071,0.53-0.168,0.53-0.374c0-0.184-0.007-0.672-0.01-1.32 c-2.159,0.469-2.614-1.04-2.614-1.04c-0.353-0.896-0.862-1.135-0.862-1.135c-0.705-0.481,0.053-0.472,0.053-0.472 c0.779,0.055,1.189,0.8,1.189,0.8c0.692,1.186,1.816,0.843,2.258,0.645c0.071-0.502,0.271-0.843,0.493-1.037 C4.86,11.425,3.049,10.76,3.049,7.786c0-0.847,0.302-1.54,0.799-2.082C3.768,5.507,3.501,4.718,3.924,3.65 c0,0,0.652-0.209,2.134,0.796C6.677,4.273,7.34,4.187,8,4.184c0.659,0.003,1.323,0.089,1.943,0.261 c1.482-1.004,2.132-0.796,2.132-0.796c0.423,1.068,0.157,1.857,0.077,2.054c0.497,0.542,0.798,1.235,0.798,2.082 c0,2.981-1.814,3.637-3.543,3.829c0.279,0.24,0.527,0.713,0.527,1.437c0,1.037-0.01,1.874-0.01,2.129 c0,0.208,0.14,0.449,0.534,0.373c3.081-1.028,5.302-3.935,5.302-7.362C15.76,3.906,12.285,0.431,7.999,0.431z"/>
              </svg>
            </span>
            <a href="https://github.com/mcneel/developer-rhino3d-com/blob/master/_samples/rhinocommon/add-twisted-cube.md" target="_blank">Edit page on GitHub</a>
          </div>
            <div class="col-md-4">
              <span class="pull-right">
                <span class="glyphicon glyphicon-cog"></span>&nbsp;<a href="/admin">Admin</a>
              </span>
            </div>
        </div>

        <div class="row text-center">
          © 1997 - 2017 Robert McNeel &amp; Associates
        </div>

      

    </div>

  </div>

  <script>
    if (navigator.appVersion.indexOf("Win")!=-1)
    {
      var body = document.getElementsByTagName("body");
      body[0].style.fontWeight = '400';
    }
  </script>

</footer>

    </div>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>

    <!-- MathJax -->
    <script type="text/javascript" src="http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>

    <script type="text/javascript">
    $('body').scrollspy({
        target: '.bs-docs-sidebar',
        offset: 150 /* fixed header is about 40px high */
    });
    </script>
    <!--
    Next block expands Bootstrap Collapse component when linked to it.  Used in rhinoscriptsyntax api docs
    ex: http://developer.rhino3d.com/api/RhinoScriptSyntax/win/#collapse-PointCompare
    -->
    <script type="text/javascript">
    $(document).ready(function () {
        if(document.title == 'rhinoscriptsyntax' && location.hash != null && location.hash != ""){
            $('.collapse').removeClass('in');
            $('#collapse-' + location.hash.split("-")[1] + '.collapse').collapse('show');
        }
    });
    </script>
  </body>

</html>
